const SEDIS = "Secretaria de Desenvolvimento e Inclusão Social";
const SOBRAS = "Secretaria de Obras";

export const data = [
  {
    id: "168.1",
    cod: "8040001",
    autor: "Alberto Barreto",
    tipo: "OSC",
    sec: SEDIS,
    benef: "AFASCOM — Santa Verônica",
    obj: "Saber para Empreender — Recepção Acolhedora",
    obj_full:
      "Custeio de recepcionista para acolhimento de adolescentes/jovens em cumprimento de medida socioeducativa (Liberdade Assistida e PSC) e demais visitantes da OSC.",
    valor: "R$ 27.000",
    valor_num: 27000,
    status: "Em processo",
    processo: "9.459/2026",
    periodo: "12 meses",
    publico: "90 adolescentes/jovens e famílias",
    crono: 0,
    pt: 1,
    nf: 0,
  },
  {
    id: "168.3",
    cod: "8040003",
    autor: "Alberto Barreto",
    tipo: "OSC",
    sec: SEDIS,
    benef: "Casa do Ancião Luísa de Marillac",
    obj: "Custeio de atividades assistenciais — idosos",
    obj_full:
      "Apoio à entidade para custeio de atividades assistenciais voltadas a idosos em situação de vulnerabilidade social.",
    valor: "R$ 20.000",
    valor_num: 20000,
    status: "Em processo",
    processo: "9.451/2026",
    periodo: "12 meses",
    publico: "Idosos em situação de vulnerabilidade social",
    crono: 0,
    pt: 1,
    nf: 0,
  },
  {
    id: "170.8",
    cod: "8040065",
    autor: "Bilili de Angelis",
    tipo: "OSC",
    sec: SEDIS,
    benef: "Casa do Ancião Luísa de Marillac",
    obj: "Custeio de atividades assistenciais — idosos",
    obj_full:
      "Apoio à entidade para custeio de atividades assistenciais voltadas a idosos em situação de vulnerabilidade social.",
    valor: "R$ 10.000",
    valor_num: 10000,
    status: "Em processo",
    processo: "9.451/2026",
    periodo: "12 meses",
    publico: "Idosos em situação de vulnerabilidade social",
    crono: 0,
    pt: 1,
    nf: 0,
  },
  {
    id: "176.8",
    cod: "8040253",
    autor: "João H. Dentinho",
    tipo: "OSC",
    sec: SEDIS,
    benef: "Casa do Ancião Luísa de Marillac",
    obj: "Custeio de atividades assistenciais — idosos",
    obj_full:
      "Apoio à entidade para custeio de atividades assistenciais voltadas a idosos em situação de vulnerabilidade social.",
    valor: "R$ 20.000",
    valor_num: 20000,
    status: "Em processo",
    processo: "9.451/2026",
    periodo: "12 meses",
    publico: "Idosos em situação de vulnerabilidade social",
    crono: 0,
    pt: 1,
    nf: 0,
  },
  {
    id: "173.4",
    cod: "8040158",
    autor: "Douglas Carbonne",
    tipo: "OSC",
    sec: SEDIS,
    benef: "Casa de Apoio Mulher e Vida",
    obj: "Estruturar para Acolher — material permanente",
    obj_full:
      "Aquisição de equipamentos e material permanente: computadores All-in-One, impressoras multifuncionais, máquinas de costura, mobiliário e climatizadores.",
    valor: "R$ 50.000",
    valor_num: 50000,
    status: "Em processo",
    processo: "9.422/2026",
    periodo: "Execução única (compra)",
    publico: "Pacientes HIV/Aids e oncológicos",
    crono: 0,
    pt: 1,
    nf: 0,
  },
  {
    id: "175.1",
    cod: "8040488",
    autor: "Jessé Silva",
    tipo: "OSC",
    sec: SEDIS,
    benef: "Casa de Apoio Mulher e Vida",
    obj: "Sustentar para Acolher — custeio operacional e RH",
    obj_full:
      "Custeio de RH (recepcionista 7 meses + aux. serviços gerais 12 meses), despesas operacionais fixas e materiais para oficinas de geração de renda e arte terapia.",
    valor: "R$ 60.000",
    valor_num: 60000,
    status: "Análise técnica",
    processo: "9.826/2026",
    periodo: "12 meses",
    publico:
      "Pessoas 18-59 anos e idosos vivendo com HIV/Aids e pacientes oncológicos",
    crono: 0,
    pt: 1,
    nf: 0,
  },
  {
    id: "184.3",
    cod: "8040488",
    autor: "Talita",
    tipo: "OSC",
    sec: SEDIS,
    benef: "Casa de Apoio Mulher e Vida",
    obj: "Sustentar para Acolher — custeio operacional e RH",
    obj_full:
      "Custeio de RH (recepcionista 7 meses + aux. serviços gerais 12 meses), despesas operacionais fixas e materiais para oficinas de geração de renda e arte terapia.",
    valor: "R$ 10.000",
    valor_num: 10000,
    status: "Análise técnica",
    processo: "9.826/2026",
    periodo: "12 meses",
    publico:
      "Pessoas 18-59 anos e idosos vivendo com HIV/Aids e pacientes oncológicos",
    crono: 0,
    pt: 1,
    nf: 0,
  },
  {
    id: "186.15",
    cod: "8040488",
    autor: "Zelinda Pastora",
    tipo: "OSC",
    sec: SEDIS,
    benef: "Casa de Apoio Mulher e Vida",
    obj: "Sustentar para Acolher — custeio operacional e RH",
    obj_full:
      "Custeio de RH (recepcionista 7 meses + aux. serviços gerais 12 meses), despesas operacionais fixas e materiais para oficinas de geração de renda e arte terapia.",
    valor: "R$ 20.000",
    valor_num: 20000,
    status: "Análise técnica",
    processo: "9.826/2026",
    periodo: "12 meses",
    publico:
      "Pessoas 18-59 anos e idosos vivendo com HIV/Aids e pacientes oncológicos",
    crono: 0,
    pt: 1,
    nf: 0,
  },
  {
    id: "179.8",
    cod: "8040488",
    autor: "Nicola Neto",
    tipo: "OSC",
    sec: SEDIS,
    benef: "Casa de Apoio Mulher e Vida",
    obj: "Sustentar para Acolher — custeio operacional e RH",
    obj_full:
      "Custeio de RH (recepcionista 7 meses + aux. serviços gerais 12 meses), despesas operacionais fixas e materiais para oficinas de geração de renda e arte terapia.",
    valor: "R$ 5.000",
    valor_num: 5000,
    status: "Análise técnica",
    processo: "9.826/2026",
    periodo: "12 meses",
    publico:
      "Pessoas 18-59 anos e idosos vivendo com HIV/Aids e pacientes oncológicos",
    crono: 0,
    pt: 1,
    nf: 0,
  },
  {
    id: "179.2",
    cod: "8040324",
    autor: "Nicola Neto",
    tipo: "OSC",
    sec: SEDIS,
    benef: "AFASCOM — Santa Verônica",
    obj: "Reforma do Corredor de Acesso",
    obj_full:
      "Reforma completa do corredor de acesso: troca de ripas e telhas tipo romana, substituição total do sistema elétrico (normas ABNT), montagem de painel elétrico e instalação de luminárias.",
    valor: "R$ 20.000",
    valor_num: 20000,
    status: "Em processo",
    processo: "9.348/2026",
    periodo: "90 dias",
    publico: "Adolescentes/jovens em medida socioeducativa e comunidade local",
    crono: 0,
    pt: 1,
    nf: 0,
  },
  {
    id: "179.6",
    cod: "8040328",
    autor: "Nicola Neto",
    tipo: "OSC",
    sec: SEDIS,
    benef: "Projeto HAPET",
    obj: "Alimentando Gerações — custeio de atividades",
    obj_full:
      "Apoio ao Projeto HAPET para custeio de atividades de assistência social voltadas à segurança alimentar e geração de renda.",
    valor: "R$ 5.000",
    valor_num: 5000,
    status: "Em processo",
    processo: "7.864/2026",
    periodo: "12 meses",
    publico: "Pessoas em situação de vulnerabilidade alimentar",
    crono: 0,
    pt: 1,
    nf: 0,
  },
  {
    id: "186.8",
    cod: "8040556",
    autor: "Zelinda Pastora",
    tipo: "OSC",
    sec: SEDIS,
    benef: "Instituto VIDA",
    obj: "Inclusão Digital — material permanente",
    obj_full:
      "Aquisição de notebooks e equipamentos duráveis para aulas de inclusão digital para crianças e adolescentes em situação de vulnerabilidade.",
    valor: "R$ 15.000",
    valor_num: 15000,
    status: "Em processo",
    processo: "9.103/2026",
    periodo: "Execução única (compra)",
    publico: "Crianças e adolescentes em vulnerabilidade social",
    crono: 0,
    pt: 1,
    nf: 0,
  },
  {
    id: "186.10",
    cod: "8040558",
    autor: "Zelinda Pastora",
    tipo: "OSC",
    sec: SEDIS,
    benef: "Associação Beneficente Vida Nova",
    obj: "Orquestra Jovem Vida Nova — custeio",
    obj_full:
      "Custeio de 4 profissionais (3 monitores de música + 1 maestro/coordenador) por 5 meses e materiais de consumo para a orquestra jovem.",
    valor: "R$ 25.000",
    valor_num: 25000,
    status: "Em processo",
    processo: "8.497/2026",
    periodo: "5 meses",
    publico: "Até 30 crianças e adolescentes de 6 a 18 anos",
    crono: 0,
    pt: 1,
    nf: 0,
  },
  {
    id: "169.35",
    cod: "8040057",
    autor: "Ariel Katz",
    tipo: "Direta",
    sec: "Secretaria de Serviços Públicos",
    benef: "Secretaria de Serviços Públicos",
    obj: "Aquisição de materiais de consumo — limpeza urbana",
    obj_full:
      "Execução de serviços de infraestrutura urbana — concluída no 1º bimestre de 2026.",
    valor: "R$ 50.000",
    valor_num: 50000,
    status: "Concluído",
    processo: "—",
    periodo: "Concluído",
    publico: "Município de Taubaté",
    crono: 1,
    pt: 0,
    nf: 1,
  },
  {
    id: "183.19",
    cod: "8040485",
    autor: "Rodson Lima Bobi",
    tipo: "Direta",
    sec: "Secretaria de Serviços Públicos",
    benef: "Secretaria de Serviços Públicos",
    obj: "Aquisição de materiais — Divisão de Funerárias e Cemitérios",
    obj_full:
      "Execução de serviços de infraestrutura urbana — concluída no 1º bimestre de 2026.",
    valor: "R$ 10.000",
    valor_num: 10000,
    status: "Concluído",
    processo: "—",
    periodo: "Concluído",
    publico: "Município de Taubaté",
    crono: 1,
    pt: 0,
    nf: 1,
  },
  {
    id: "179.37",
    cod: "8040359",
    autor: "Nicola Neto",
    tipo: "Direta",
    sec: "Secretaria de Serviços Públicos",
    benef: "Secretaria de Serviços Públicos",
    obj: "Aquisição de equipamentos da Secretaria de Serviços Públicos",
    obj_full:
      "Execução de serviços de infraestrutura urbana — concluída no 1º bimestre de 2026.",
    valor: "R$ 30.000",
    valor_num: 30000,
    status: "Concluído",
    processo: "—",
    periodo: "Concluído",
    publico: "Município de Taubaté",
    crono: 1,
    pt: 0,
    nf: 1,
  },
  {
    id: "178.32",
    cod: "8040322",
    autor: "Neneca Luiz Henrique",
    tipo: "Direta",
    sec: "Secretaria de Serviços Públicos",
    benef: "Secretaria de Serviços Públicos",
    obj: "Manutenção de veículos — Departamento de Operações",
    obj_full:
      "Aquisição e instalação de persianas para unidades da Secretaria de Desenvolvimento e Inclusão Social. Execução: 85% concluída.",
    valor: "R$ 5.000",
    valor_num: 5000,
    status: "Em processo",
    processo: "—",
    periodo: "Previsão: Maio/2026",
    publico: "Unidades municipais da SEDIS",
    crono: 1,
    pt: 0,
    nf: 0,
  },
  {
    id: "169.32",
    cod: "8040054",
    autor: "Ariel Katz",
    tipo: "Direta",
    sec: "Secretaria de Serviços Públicos",
    benef: "Secretaria de Serviços Públicos",
    obj: "Aquisição de equipamentos — Secretaria de Serviços Públicos",
    obj_full:
      "Aquisição de mobiliário e equipamentos de informática para unidades da SEDIS. Execução: 76% concluída.",
    valor: "R$ 50.000",
    valor_num: 50000,
    status: "Em processo",
    processo: "—",
    periodo: "Previsão: Maio/2026",
    publico: "Unidades municipais da SEDIS",
    crono: 1,
    pt: 0,
    nf: 0,
  },
  {
    id: "186.2",
    cod: "8040550",
    autor: "Zelinda Pastora",
    tipo: "Direta",
    sec: "Secretaria de Desenvolvimento, Inovação e Turismo",
    benef: "SEBRAE — Parceria capacitação empreendedora",
    obj: "Parceria para custeio de cursos do SEBRAE",
    obj_full:
      "Parceria com o SEBRAE formalizada via Contrato 68/2026. Vigência de 12 meses.",
    valor: "R$ 20.112",
    valor_num: 20112,
    status: "Em processo",
    processo: "—",
    periodo: "12 meses (2026-2027)",
    publico: "Rede assistencial do município",
    crono: 1,
    pt: 0,
    nf: 0,
  },
  {
    id: "184.42",
    cod: "8040527",
    autor: "Talita",
    tipo: "Direta",
    sec: "Secretaria de Serviços Públicos",
    benef: "Secretaria de Serviços Públicos",
    obj: "Disponibilização de banheiros químicos nas feiras livres",
    obj_full:
      "Recurso devolvido ao fundo de origem por inexequibilidade no exercício de 2026.",
    valor: "R$ 25.000",
    valor_num: 25000,
    status: "Devolvida",
    processo: "—",
    periodo: "—",
    publico: "—",
    crono: 0,
    pt: 0,
    nf: 0,
  },
  {
    id: "181.65",
    cod: "8040440",
    autor: "Professor Edson",
    tipo: "Direta",
    sec: "Secretaria de Serviços Públicos",
    benef: "Secretaria de Serviços Públicos",
    obj: "Instalação de postes — viela Rua João Paulo de Oliveira Gama, Jd. América",
    obj_full:
      "Recurso devolvido ao fundo de origem por inexequibilidade no exercício de 2026.",
    valor: "R$ 5.000",
    valor_num: 5000,
    status: "Devolvida",
    processo: "—",
    periodo: "—",
    publico: "—",
    crono: 0,
    pt: 0,
    nf: 0,
  },
];